"use client";

import { useState } from "react";

export default function AdminConsole() {
  const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [projectId, setProjectId] = useState(""); const [summaryId, setSummaryId] = useState("");
  async function post(path: string, init: RequestInit = {}) { const response = await fetch(path, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init.headers ?? {}) } }); const data = await response.json() as { id?: string; status?: string; error?: string; projects?: unknown[]; }; setMessage(data.error ?? JSON.stringify(data)); if (data.id) setProjectId(data.id); return data; }
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await post("/api/admin/projects", { method: "POST", body: form }); }
  return <><section><label htmlFor="token">Admin bearer token</label><input id="token" type="password" value={token} onChange={(event) => setToken(event.target.value)} /></section><form onSubmit={create}><h2>Nuevo proyecto</h2><label htmlFor="title">Título</label><input id="title" name="title" required /><label htmlFor="description">Descripción</label><textarea id="description" name="description" required /><label htmlFor="categorySlugs">Categorías (slugs separados por coma)</label><input id="categorySlugs" name="categorySlugs" required /><label htmlFor="file">PDF</label><input id="file" name="file" type="file" accept="application/pdf" required /><button type="submit">Guardar borrador</button></form><section><h2>Procesar y publicar</h2><label htmlFor="projectId">ID de proyecto</label><input id="projectId" value={projectId} onChange={(event) => setProjectId(event.target.value)} /><label htmlFor="summaryId">ID de resumen aprobado tras procesar</label><input id="summaryId" value={summaryId} onChange={(event) => setSummaryId(event.target.value)} /><div className="grid"><button type="button" onClick={() => void post(`/api/admin/projects/${projectId}/process`, { method: "POST" })}>Procesar PDF y resumen</button><button type="button" onClick={() => void post(`/api/admin/projects/${projectId}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ summaryId }) })}>Aprobar resumen</button><button type="button" onClick={() => void post(`/api/admin/projects/${projectId}/publish`, { method: "POST" })}>Publicar</button></div></section>{message && <p role="status">{message}</p>}</>;
}
